version: "3.8"
services:
  mongodb:
    build: ./Data
    container_name: mongodb
    ports:
    - "27017:27017"
    restart: unless-stopped
  backend:
    build: ./Backend
    container_name: api
    ports:
      - "1405:1405"
    depends_on:
      - mongodb
  frontend:
    build: ./Frontend/meal-planner
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - backend
